version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: bookstore-postgres
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bookstore-network

  redis:
    image: redis:7-alpine
    container_name: bookstore-redis
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save ""
      --loglevel warning
      --databases 1
    volumes:
      - redis_data:/data
    networks:
      - bookstore-network

  swagger:
    image: swaggerapi/swagger-ui
    container_name: bookstore-swagger
    ports:
      - "8081:8080"
    environment:
      URLS: "[{ url: 'http://app:8085/v3/api-docs', name: 'BookShopAPI' }]"
    depends_on:
      - app
    networks:
      - bookstore-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore-app
    ports:
      - "8080:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookstore
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
        - bookstore-network


volumes:
  postgres_data:
  redis_data:

networks:
  bookstore-network:
    driver: bridge
      

